### ISSUE TITLE
typo: code example incorrect

### ISSUE THREAD

**Issue by espinielli** [douglascrockford/RQ#15]
The example for requestorize has a typo IMHO at [line 210](https://github.com/douglascrockford/RQ/blob/master/help.html#L210).

It says

    var fullname_requestor = requestorize(fullname_requestor);

but it should be:

   var fullname_requestor = requestorize(make_fullname);

HTH

**Comment by espinielli** [comment]
I see it was already reported in #12 but it is not yet reflected in the html and web...

**Comment by douglascrockford** [comment]
Thanks.
