### ISSUE TITLE
bug, or unclear doc, in delay_requestor example

### ISSUE THREAD

**Issue by oresmus** [douglascrockford/RQ#16]
help.html contains:

<h3>Delay Requestor</h3>
<p>The <code>delay_requestor</code> inserts a delay into a sequence without blocking. </p>
<pre>function delay_requestor(callback, value) {
    var timeout_id = setTimeout(callback, 1000);
    return function cancel(reason) {
        return clearTimeout(timeout_id);
    };
}</pre>

If I understand that documentation correctly, this is meant to be used in series with other requestors in the argument to RQ.sequence. If I'm right, I think it has a bug, since it should use its value parameter in the same way identity_requestor does. If I'm wrong, then IMHO the documentation is not clear, and an example of intended usage would be helpful.

Similar comments apply to the "Delay Factory" which follows this function.

**Comment by douglascrockford** [comment]
Thanks
