### ISSUE TITLE
RQ.parallel should be able to accept objects

### ISSUE THREAD

**Issue by EvgenyOrekhov** [douglascrockford/RQ#20]
When using RQ.parallel, I always don't care about order and care about giving names to results, so I always end up using the construct factory. It would be better if RQ.parallel could accept objects:

```js
getStuff = RQ.parallel({
    nav: getNav,
    ads: getAds,
    weather: getWeather,
    messageOfTheDay: getMessageOfTheDay
}, {
    horoscope: getHoroscope,
    gossip: getGossip
});
```

**Comment by nikoskalogridis** [comment]
Have a look here http://www.rq.crockford.com/ at the last section (construct function) It does exactly what you are looking for

**Comment by EvgenyOrekhov** [comment]
@nikoskalogridis I am suggesting this change specifically to eliminate the need of a construct function.

**Comment by douglascrockford** [comment]
Thanks. Please try it now.
