### ISSUE TITLE
Floating point arithmetic 

### ISSUE THREAD

**Issue by S6Regen** [douglascrockford/RQ#22]
I was watching one of your presentations on YouTube and I saw your idea for better floating point arithmetic.  There is also this idea: [https://youtu.be/N05yYbUZMSQ](url)

**Comment by GrosSacASac** [comment]
real link [https://youtu.be/N05yYbUZMSQ](https://youtu.be/N05yYbUZMSQ)

maybe post it here it is more relevant [https://github.com/douglascrockford/DEC64](https://github.com/douglascrockford/DEC64)
