### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by nekdolan** [douglascrockford/RQ#23]
Is it possible to add an exception handler to RQ and if it is not, should it be possible?
Right now I am looking for a async lib that can do that.

Of curse normally we would never raise an exception manually, but if it happens accidentally should we not have the ability to handle it more gracefully than crashing the app? Of course we could put all our functions in try-catch blocks but that seems to me to be a bit excessive.

In expressJS in production if an exception is raised inside a route we normally log the error and send back a http error, however if an exception is raised in a async callback the server will just simply crash unless we catch any and all exceptions, and even if we do that we won't be able to respond properly to our user's http request.

So my idea for a possible solution is that any time a RQ.sequence or similar function is called we should have the ability to define an exception handler. If this function is defined than all functions in the RQ.sequence are put inside try catch blocks and if a error is raised the exception handler is called with the error and all other execution stops. This would allow us to fail in a more graceful way.

In the case of Promises exceptions are put in the fail category, but I think that is wrong since that way we cannot tell if the fail branch was called intentionally or not.

Apologies if I made the wrong assumption somewhere.

**Comment by douglascrockford** [comment]
You need to be careful with exceptions in asynchronous systems. The maximum effectiveness of an exception handler is a single turn. RQ will trap such exceptions and deliver them as the failure state.

**Comment by nekdolan** [comment]
Is there no value in differentiating between the asynchronous call failing and the code throwing an exception?

**Comment by nekdolan** [comment]
> RQ will trap such exceptions and deliver them as the failure state. 
I think this version of RQ cannot catch any exceptions. I tried it. There are no `try/catch` blocks in the code.

**Comment by douglascrockford** [comment]
Errors must be delivered through the callbacks. Do not be throwing exceptions.

**Comment by nekdolan** [comment]
I am not saying that I want to intentionally throw an exception. I am more concerned about the case when it happens unintentionally. There are cases when catching exceptions is better than crashing: https://expressjs.com/en/advanced/best-practice-performance.html#handle-exceptions-properly .

**Comment by douglascrockford** [comment]
The whole point to RQ is to allow processing to extend over many turns. Exceptions can not escape their turn.
