### ISSUE TITLE
Can a failure reason be false?

### ISSUE THREAD

**Issue by IDisposable** [douglascrockford/RQ#8]
On line https://github.com/douglascrockford/RQ/blob/master/rq.js#L233 we've got 
```js
return finish(undefined, reason || true);
```
This seems like it might give surprising behaviour if someone passes any falsy value for the ```reason``` variable. I assume the expected use case is the coalescing of ```undefined```, but this will also fall back to ```true``` for ```false```, ```0```, ```""```, ```NaN``` and ```null```. Of those, I could see ```null``` as possibly expected.

What do you think? Is this a least-surprise violation?
(also on https://github.com/douglascrockford/RQ/blob/master/rq.js#L335 )

**Comment by douglascrockford** [comment]
I think all of the falsy values are unreasonable in this position.
